application: rate-exchange
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:

-   url: /robots.txt
    static_files: robots.txt
    upload: robots.txt

-   url: /.*
    script: main.app